# Source https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/two-tier

get:
	wget https://raw.githubusercontent.com/terraform-providers/terraform-provider-aws/master/examples/two-tier/main.tf
	wget https://raw.githubusercontent.com/terraform-providers/terraform-provider-aws/master/examples/two-tier/outputs.tf
	wget https://raw.githubusercontent.com/terraform-providers/terraform-provider-aws/master/examples/two-tier/variables.tf


